### ISSUE TITLE
shift: can't shift that many after #17 was merged

### ISSUE THREAD

**Issue by oryband** [dennishafemann/tmux-cssh#18]
```bash
$ tmux-cssh -ns -ts 1234 -c $KEY server-name -sc root@ip server-name-2 -sc root@ip2
/usr/local/bin/tmux-cssh: 130: shift: can't shift that many
```
`server-name` and `ip` are just a string and an ip address. `$KEY` is the path to the key I use.

This started happening after pulling the latest changes #17 . Something seems to be broken.

**Comment by dennishafemann** [comment]
Thanks for your help, mentioning it. I fixed it with commit 9bc5306453fb7c9007540f1d7064cbfcfee73867.
