### ISSUE TITLE
This isn't an issue but a question - a way to identify each pane

### ISSUE THREAD

**Issue by jeffmacdonald** [dennishafemann/tmux-cssh#25]
Is it possible to a small bar with `uname -a` in it to identify each window?

Also, what is the difference between -dc and -ds

**Comment by dennishafemann** [comment]
Hi Jeff,

sorry for the delayed answer. Here it is.

* Maybe I'm thinking about to add this in a kind of way in future, but for
now you have to do it by yourself. For example, when you logged on using
tmux-cssh on one or multiple servers you can then execute following command
to set the machines name to the right tmux-status-bar.

printf '\033]2;%s\033\\' "$(uname -a)"
(or any other command)

This puts the information of the executed command into the tmux's status
bar.

* Actually there is no difference between -dc (--dont-clusterize) and -ds
(--dont-synchronize), except that tmux "synchronizes" the keystrokes to
each panes and tmux-cssh is a "clustering" tool, so I wanted to use a name
similar to it, so "dont-clusterize" was born. That's it, no difference.

Hope my answers may statisfy you, cya.

Best Regards,

Dennis

**Comment by stig** [comment]
You can also do `export PS1="$(uname -a) $ "`, but it's terribly noisy. If you're a bash user, setting PS1 to the somewhat less verbose `[\u@\H \W]# ` might help.
