### ISSUE TITLE
Not an Issue But A Question - When ds Is Used How Do You Move Between Windows

### ISSUE THREAD

**Issue by fuzzygroup** [dennishafemann/tmux-cssh#26]
Hi, 

I love the concept but one thing that I'm confused by is how to move between windows.  For example if I launch a tmux-cssh session with 3 windows and the -ds option, the focus is set to the last machine I logged into.  If I'm maintaining multiple boxes, how do I move to a different window to do something on a different box.

Wonderful work.  Thank you so much for it.

**Comment by fuzzygroup** [comment]
Got it -- prefix key plus arrow key.  I think that this would be useful info to add into to the readme with a note that your tmux configuration file might make this not work (one of my boxes was missing a config file and since this was the last box I logged into I couldn't get anywhere until I changed the order I was logging into them by).

**Comment by dennishafemann** [comment]
Hi,

This is actually not a behaviour of tmux-cssh but from tmux itself... so,
from default hit the command stroke first, default CTRL-b, then
CTRL-Up-Cursor-Key... It should move a pane up, e.g. use a Left-Arrow-Key
to move left. It's a tmux key mapping. By the way, watch CTRL-b ? For a
small overview of shortcuts.

Hope that's helps you out.

Best regards, Dennia
Am 25.05.2016 17:03 schrieb "J. Scott Johnson" <notifications@github.com>:
