### ISSUE TITLE
Don't synchronize panes after startup

### ISSUE THREAD

**Issue by tukushan** [dennishafemann/tmux-cssh#31]
After startup, is there a way to disable synchronization between panes and only send commands to a single pane, then switch synchronization back on?

Sometimes after executing a few commands on both panes, one or the other ends up in a different state from the other, and so this would allow you to send commands to that session to get its state back in sync. Clusterssh has this capability.

**Comment by dennishafemann** [comment]
Hi tukushan. sorry, for the late answer.

As a wordaround you can use two tmux-specific commands to "disable" synchronization.

* STRG-B Z ... makes the current pane the only one, mean it'll be fullscreen-sized. There you can execute all your specific commands and then re-scale via STRG-B Z

* Shut off synchronization ... Go into command-mode via STRG-B, then execute "set synchronize-panes off" or "... on".

Hope that helps.
