### ISSUE TITLE
How do I stop synchronising panes for specific time/commands

### ISSUE THREAD

**Issue by rajeshksv** [dennishafemann/tmux-cssh#33]
Say I started ssh on 3 servers using

tmux-cssh server1 server2 server3

Now after running a few commands, I realized that I need to do something specific on server2. How do I do it, without touching server1 and server3?

Also may be after running some commands only on server2, I might want again to repeat commands on all servers. Is there any toggle ?

**Comment by grimm26** [comment]
Yes, tmux has this option.  I bind it in my tmux.conf like so:
`bind C-s set-window-option synchronize-panes`

**Comment by dennishafemann** [comment]
Hi Mac,

yes, it's a feature of tmux itself... Here are some actions you can do for
what you want to do:

Enable/Disable synchronization:

In tmux execute the command "set synchronize-panes off" or "on" for
switching it. E.g.

STRG-B -> : -> set synchronize-panes off

... or ...

STRG-B -> z

... for maximize the current window, for the synchronization is also
disabled.

Best regards.
Dennis


----------
Rubik's Cube OLL / PLL Trainer
<http://www.rubiks-cube-3x3x3-oll-pll-trainer.de/> - OLL/PLL mit einer
Schritt-Für-Schritt-Anleitung, Timer-Möglichkeit, verschiedenen
Training-Methoden und einer Habe-ich-es-richtig-gemacht?-Visualisierung
erlernen.

Spiral Designer Kids <http://www.spiral-designer-kids.de/> - Leicht
gemacht, Spiralen malen für kleine kreative Köpfe

www <http://dennishafemann.de/> und weitere Android Apps
<http://android-apps.dennishafemann.de>

2017-08-07 16:59 GMT+02:00 Mark Keisler <notifications@github.com>:

**Comment by rajeshksv** [comment]
Wow, Awesome. That's exactly what I was looking for!

**Comment by fabidick22** [comment]
Hi, 

I can have only two panes synchronized and other without synchronizing?
