### ISSUE TITLE
Multiple tmux-cssh sessions not working

### ISSUE THREAD

**Issue by rajeshksv** [dennishafemann/tmux-cssh#34]
Running tmux-cssh s1 s2 s3 opens three hosts in a session

Now at same time, in a new terminal, if i open tmux-cssh c1 c2 it opens previous session instead of opening these hosts. Only one session is supported at a time ?

**Comment by dennishafemann** [comment]
Hi,

no, tmux-cssh supports, like tmux does itself, multiple sessions. Take a
look at the --help and use -ts [name] or -ns for multiple sessions.

Best regards.
Dennis

2017-08-23 9:38 GMT+02:00 Mac <notifications@github.com>:

**Comment by rajeshksv** [comment]
tmux-cssh -ts c1 c2 (created new session). Thanks!
